### ISSUE TITLE
`meow auth` command enhancements

### ISSUE THREAD

**Issue by JACoW-org** [JACoW-org/CAT#10]
have `./venv/bin/python3 -m meow auth -list` list "usernames" as well, not only keys
Possibly make the `-check` also use usernames in addition to keys (e.g.: conf2030@indico.jacow.org)

**Comment by fmeneghetti** [comment]
```
./venv/bin/python3 -m meow auth -list

conf2023:XXXXXXXXXXXXXXXXXXXXXXXXXX@indico.jacow.org (2024-10-31T11:36:34.015359)


./venv/bin/python3 -m meow auth -check XXXXXXXXXXXXXXXXXXXXXXXXXX

conf2023:XXXXXXXXXXXXXXXXXXXXXXXXXX@indico.jacow.org (2024-10-31T11:36:34.015359)

```

**Comment by JACoW-org** [comment]
```
$ ./venv/bin/python -m meow auth -check CONF2038
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/cat/meow/meow/__main__.py", line 1066, in <module>
    main()
  File "/opt/cat/meow/meow/__main__.py", line 1062, in main
    args.func(args)  # execute requested command
    ^^^^^^^^^^^^^^^
  File "/opt/cat/meow/meow/__main__.py", line 163, in meow_auth
    run(_run)
  File "/opt/cat/meow/venv/lib/python3.11/site-packages/anyio/_core/_eventloop.py", line 74, in run
    return async_backend.run(func, args, {}, backend_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/cat/meow/venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2034, in run
    return runner.run(wrapper())
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/cat/meow/venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2022, in wrapper
    return await func(*args)
           ^^^^^^^^^^^^^^^^^
  File "/opt/cat/meow/meow/__main__.py", line 151, in _run
    user = res[0].decode('utf-8')
           ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'decode'
```

Same error if using 
```
./venv/bin/python3 -m meow auth -check conf2023:XXXXXXXXXXXXXXXXXXXXXXXXXX@indico.jacow.org
```
or, in general, everything but only the api key.

**Comment by JACoW-org** [comment]
Moreover,
```
$ ./venv/bin/python -m meow auth -login  CONF2038@indico.jacow.org
```
now gives as a result the full username/apykey/server/timestamp in one string only:
```
CONF2038:XXXXXXXXXXXXXXXXXXXXXXXXXX@indico.jacow.org (2024-12-05T10:41:43.648850)
```
while before it was giving out the username/key only  separately:
```
CONF2038 indico.jacow.org XXXXXXXXXXXXXXXXXXXXXXXXXX
```
Since PURR will ask for the key only, the new, single, string could be confusing.
I'd prefer the previous outocme syntax of the `auth -login` command

**Comment by fmeneghetti** [comment]
now the check command does not fail if the provided key is invalid:

``` 
./venv/bin/python3 -m meow auth -check pippo
invalid auth key
```

**Comment by fmeneghetti** [comment]
we have now adopted the following output format for the -list and -check commands

```
./venv/bin/python3 -m meow auth -list
[2024-02-05T18:09:54.854840] - user=CONF2038 host=indico.jacow.org auth=XXXXXXXXXXXXXXXXXXXXXXXXXX
```

```
./venv/bin/python3 -m meow auth -check XXXXXXXXXXXXXXXXXXXXXXXXXX
[2024-02-05T18:09:54.854840] - user=CONF2038 host=indico.jacow.org auth=XXXXXXXXXXXXXXXXXXXXXXXXXX
```

**Comment by JACoW-org** [comment]
completed and deployed in December 2024
